apiKey: ""
mongoUri: "mongodb://localhost:27017/weatherdb"
database: "weatherdb"
citiesCollection: "cities"
apiBase: "https://api.weatherstack.com/current"
swagger:
  resourcePackage: "com.himanshu.weather.resources"
  title: "Weather API"
  description: "Weather API Documentation"
  version: "1.0.0"
  schemes:
    - "http"
  host: "localhost:8080"
  contact: "Himanshu (himanshu@example.com)"  # Change contact to a string
